# this compose file use for dev only

version: "3.5"

services:
  ludo-colyseus-test:
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./src:/home/app/src:rw
    ports:
      - 2567:2567
    network_mode: host

